
model_layers = 8
max_seq_length = 1024
snac_model_name = "hubertsiuzdak/snac_24khz"
whisper_model_name = "small"

[model_config]


[token_config]
text_vocab_size = 151936
audio_vocab_size = 4096
text_special_tokens = 64
audio_special_tokens = 64


[task_mapping]
stage_1 = "A1T1"
stage_2 = "AT"
stage_3 = "A1A2"

[stage_1]
lr = 1e-3
min_lr = 4e-6
max_steps = 17000
warmup_steps = 0.1
scheduler_interval = "step"
dataset = "asr_dataset"


[stage_2]
lr = 4e-4
min_lr = 4e-6
max_steps = 27000
warmup_steps = 0.1
scheduler_interval = "step"
dataset = "text_qa_dataset"

[stage_3]
lr = 4e-4
min_lr = 4e-6
max_steps = 50000
warmup_steps = 0.1
scheduler_interval = "step"
dataset = "mix_qa_dataset"
