
model_layers = 8
max_seq_length = 2048
snac_model_name = "hubertsiuzdak/snac_24khz"
whisper_model_name = "small"

[model_config]


[token_config]
text_vocab_size = 151936
audio_vocab_size = 4096
text_special_tokens = 64
audio_special_tokens = 64


[task_mapping]
stage_1 = "asr"
stage_2 = "AT"
stage_3 = "A1A2"
