
model_layers = 8
max_seq_length = 1024
snac_model_name = "hubertsiuzdak/snac_24khz"
whisper_model_name = "small"

[model_config]


[token_config]
text_vocab_size = 151936
audio_vocab_size = 4096
text_special_tokens = 64
audio_special_tokens = 64


[stage_1]
lr = 1e-3
min_lr = 4e-6
max_steps = 17000
warmup_steps = 0.1
scheduler_interval = "step"
datasets = "asr_dataset"
sampling_weights = [1.0]
train_data_dir = "datasets/train"
valid_data_dir = "random"

[stage_2]
lr = 4e-4
min_lr = 4e-6
max_steps = 27000
warmup_steps = 0.1
scheduler_interval = "step"
datasets = ["asr_dataset", "text_qa_dataset"]
sampling_weights = [1.0, 1.0]
train_data_dir = "datasets/train"
valid_data_dir = "random"

[stage_3]
lr = 4e-4
min_lr = 4e-6
max_steps = 50000
warmup_steps = 0.1
scheduler_interval = "step"
datasets = ["asr_dataset", "text_qa_dataset", "voice_qa_dataset"]
sampling_weights = [1.0, 1.0, 1.0]
train_data_dir = "datasets/train"
valid_data_dir = "random"
